<?php
///** @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer */
//
//$filter = $block->getFilter();
//if (!$filter) {
//    return;
//}
//
//$items = $filter->getItems();
//if (empty($items)) {
//    return;
//}
//?>
<!---->
<!--<ol class="items">-->
<!--    --><?php //foreach ($items as $_item): ?>
<!--        <li class="item">-->
<!--            <label>-->
<!--                <input type="checkbox"-->
<!--                    --><?php //= $_item->getIsSelected() ? 'checked' : '' ?>
<!--                       onclick="location.href='--><?php //= $block->escapeUrl($_item->getUrl()) ?>//'">
//
//                <?php //= $block->escapeHtml($_item->getLabel()) ?>
<!---->
<!--                --><?php //if ($block->shouldDisplayProductCount()): ?>
<!--                    (--><?php //= (int) $_item->getCount() ?><!--)-->
<!--                --><?php //endif; ?>
<!--            </label>-->
<!--        </li>-->
<!--    --><?php //endforeach; ?>
<!--</ol>-->
