<?php

/** @var \Magento\Newsletter\Block\Subscribe $block */
if (!$block->getButtonLockManager()) {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $block->setButtonLockManager(
        $objectManager->get(\Magento\Framework\View\Element\ButtonLockManager::class)
    );
}
/** @var $escaper \Magento\Framework\Escaper */
?>
<div class="block newsletter">
    <div class="title">
        <h1>
            <?= __(
                'Register in our %1newsletter%2',
                '<span>',
                '</span>'
            ) ?>
        </h1>
    </div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">

            <!-- Campo Nome -->
            <div class="field newsletter-name">
                <div class="control">
                    <label for="newsletter-name">
                        <span class="label">
                            <?= $escaper->escapeHtml(__('Name')) ?>
                        </span>
                        <input name="name" type="text" id="newsletter-name"
                            placeholder="<?= $escaper->escapeHtml(__('Enter your name')) ?>"
                            data-validate="{required:true}" />
                    </label>
                </div>
            </div>

            <!-- Campo Email (nativo) -->
            <div class="field newsletter-email">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $escaper->escapeHtml(__('Email')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                            placeholder="<?= $escaper->escapeHtml(__('Enter your email address')) ?>"
                            data-mage-init='{"mage/trim-input":{}}'
                            data-validate="{required:true, 'validate-email':true}" />
                    </label>
                </div>
            </div>

            <!-- Campo Privacidade -->
            <div class="field newsletter-privacy">
                <div class="control">
                    <label for="newsletter-privacy">
                        <!-- Garante que sempre existe um valor (0 ou 1) -->
                        <input type="hidden" name="privacy" value="0" />
                        <input type="checkbox" name="privacy" id="newsletter-privacy" value="1"
                            data-validate="{required:true}" />
                        <strong><?= __('I agree with the %1Privacy Policy%2', '<a href="#" class="privacy-policy-link" target="_blank">', '</a>') ?></strong>
                    </label>
                </div>
            </div>

            <!-- Botão -->
            <div class="actions">
                <button class="action subscribe primary"
                    title="<?= $escaper->escapeHtmlAttr(__('register')) ?>"
                    type="submit"
                    aria-label="Subscribe"
                    <?php if ($block->getButtonLockManager()->isDisabled('newsletter_form_submit')): ?>
                    disabled="disabled"
                    <?php endif; ?>>
                    <span><?= $escaper->escapeHtml(__('register')) ?></span>
                </button>
            </div>
        </form>
        <!-- bloco para mensagem de retorno de inscrição da newsletter -->
        <div class="newsletter-messages"></div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Avanti_NewsletterExtend/js/newsletter-submit": {}
    }
}
</script>

<!-- script para os textos com i18n -->
<script>
    window.newsletterSuccessMessage = '<?= $escaper->escapeJs(__('Thank you for subscribing.')) ?>';
    window.newsletterErrorMessage   = '<?= $escaper->escapeJs(__('Something went wrong. Try again.')) ?>';
</script>

