<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis


/**
* Category view template
*
* @var $block \Magento\Framework\View\Element\Template
*/


?>

<?php
/** @var \Magento\Customer\Model\Session $customerSession */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get(\Magento\Customer\Model\Session::class);

// se o usuário não estiver logado mostra a string "ou"
if (!$customerSession->isLoggedIn()): ?>
    <li class="header-links-or">
        <?= __('ou') ?>
    </li>
<?php endif; ?>