<?php
/** @var \Magento\Framework\View\Element\Template $block */

$customerSession = $block->getLayout()
    ->getBlock('customer.session');

if (!$customerSession) {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get(\Magento\Customer\Model\Session::class);
}

if (!$customerSession->isLoggedIn()): ?>
    <span class="or-separator"><?= __('or') ?></span>
<?php endif; ?>
